runtime: python39

# Environment variables for production
env_variables:
  GOOGLE_CLOUD_PROJECT: url-shortener-luis-2025-dac25
  FIRESTORE_COLLECTION: url_mappings
  FLASK_DEBUG: false
  SECRET_KEY: prod-secret-key-url-shortener-2025-secure
  USE_MOCK_DATABASE: false

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Instance configuration
instance_class: F1

# Static file handling
handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always

# Health check configuration
readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2
